stages:
  - test
  - beta
cache:
  key: ${CI_PROJECT_PATH_SLUG}
  paths:
    - vendor/bundle
before_script:
  - "bundle install --path vendor/bundle"
  - "tuist fetch"
  - "tuist generate --no-open"
variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

test_mobile:
  dependencies: []
  stage: test
  artifacts:
    paths:
      - fastlane/screenshots
      - fastlane/logs
      - fastlane/test_output
  script:
    - "bundle exec fastlane test"
  tags:
    - xcode

test_vision:
  dependencies: []
  stage: test
  script:
    - "pwsh ./scripts/test-vision.ps1"

beta_mobile:
  dependencies: []
  stage: beta
  artifacts:
    paths:
      - fastlane/screenshots
      - fastlane/logs
  script:
    - "bundle exec fastlane beta"
  tags:
    - xcode
  only:
    - /^release\/(.*)$/

beta_vision:
  dependencies: []
  stage: test
  script:
    - "pwsh ./scripts/archive-vision.ps1"
